version: '3.8'
services:
  web:
    build: .
    ports:
      - "9000:9000"
    environment:
      - SysEnv=testing
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zuruck
      POSTGRES_DB: document_platform_db
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: